eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-Url.defaultZone=http://localhost:9761/eureka/
server.port=9761
spring.security.user.name=eureka
spring.security.user.password=password

spring.application.name=discovery-server

# Enable tracing
management.tracing.enabled=true
management.tracing.sampling.probability=1.0

# Correct Zipkin endpoint (this is the correct one)
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
