spring.application.name=product-service
logging.level.org.testcontainers=DEBUG

server.port=0
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://eureka:password@localhost:9761/eureka
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost

# Enable tracing
management.tracing.enabled=true
management.tracing.sampling.probability=1.0

# Correct Zipkin endpoint (this is the correct one)
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
